import { Language, User, Tag } from './types';

export const TRANSLATIONS = {
  cn: {
    welcome: "加入自习室",
    roomId: "房间号",
    password: "密码",
    join: "加入",
    create: "创建",
    chat: "聊天室",
    aiHelp: "AI 助教",
    media: "播放",
    leaderboard: "排行榜",
    blocker: "屏蔽网页",
    focus: "倒计时",
    shortBreak: "休息",
    longBreak: "长休息",
    stopwatch: "正计时",
    start: "开始",
    pause: "暂停",
    resume: "继续",
    reset: "重置",
    end: "结束",
    tags: "标签",
    forest: "我的森林",
    stats: "统计",
    studying: "学习中",
    resting: "休息中",
    idle: "闲置",
    placeholderMessage: "输入消息 (@ai 提问)...",
    aiPlaceholder: "向 AI 老师提问...",
    mic: "麦克风",
    cam: "摄像头",
    noiseCancel: "降噪",
    addTag: "添加标签",
    blockSitePlaceholder: "输入网址 (例如: weibo.com)",
    you: "你",
    note: "便笺",
    export: "导出",
    theme: "主题",
    language: "语言",
    enterUrl: "输入播放地址",
    add: "添加",
    fullscreen: "全屏",
    minimize: "缩小",
    loginError: "房间号或密码错误",
    roomExists: "房间已存在",
    roomNotFound: "房间不存在",
    roomFull: "房间已满（仅支持两人）",
  },
  en: {
    welcome: "Join Study Room",
    roomId: "Room ID",
    password: "Password",
    join: "Join",
    create: "Create",
    chat: "Chat Room",
    aiHelp: "AI Tutor",
    media: "Media Player",
    leaderboard: "Leaderboard",
    blocker: "Web Blocker",
    focus: "Countdown",
    shortBreak: "Break",
    longBreak: "Long Break",
    stopwatch: "Stopwatch",
    start: "Start",
    pause: "Pause",
    resume: "Resume",
    reset: "Reset",
    end: "End",
    tags: "Tags",
    forest: "My Forest",
    stats: "Statistics",
    studying: "Studying",
    resting: "On Break",
    idle: "Idle",
    placeholderMessage: "Type a message (@ai to ask)...",
    aiPlaceholder: "Ask AI Tutor...",
    mic: "Mic",
    cam: "Camera",
    noiseCancel: "Noise Cancellation",
    addTag: "Add Tag",
    blockSitePlaceholder: "Enter URL (e.g., twitter.com)",
    you: "You",
    note: "Sticky Note",
    export: "Export",
    theme: "Theme",
    language: "Language",
    enterUrl: "Enter Media URL",
    add: "Add",
    fullscreen: "Fullscreen",
    minimize: "Minimize",
    loginError: "Invalid Room ID or Password",
    roomExists: "Room already exists",
    roomNotFound: "Room not found",
    roomFull: "Room is full (2 people max)",
  }
};

export const MOCK_USERS: User[] = [
  { id: '1', name: 'Alice', avatar: 'https://picsum.photos/100/100?random=1', isSelf: false, isMicOn: true, isCamOn: true, status: 'focus', studyTimeMinutes: 45 },
  { id: '2', name: 'Bob', avatar: 'https://picsum.photos/100/100?random=2', isSelf: false, isMicOn: false, isCamOn: true, status: 'break', studyTimeMinutes: 120 },
  { id: '3', name: 'Charlie', avatar: 'https://picsum.photos/100/100?random=3', isSelf: false, isMicOn: false, isCamOn: false, status: 'focus', studyTimeMinutes: 30 },
  { id: '4', name: 'David', avatar: 'https://picsum.photos/100/100?random=4', isSelf: false, isMicOn: true, isCamOn: true, status: 'idle', studyTimeMinutes: 10 },
];

export const DEFAULT_TAGS: Tag[] = [
  { id: '1', name: 'Study', color: '#34D399' },
  { id: '2', name: 'Work', color: '#60A5FA' },
  { id: '3', name: 'Reading', color: '#F472B6' },
];

export const LOFI_URLS = [
  { name: 'Lofi Girl', url: 'https://www.youtube.com/embed/jfKfPfyJRdk?autoplay=0' },
  { name: 'Coffee Shop', url: 'https://www.youtube.com/embed/e3L1PIY1ykE?autoplay=0' },
  { name: 'Bilibili Lofi', url: 'https://www.bilibili.com/blackboard/live/live-activity-player.html?cid=27519423&quality=0' }
];
